- name: join with master
  command: kubeadm join --ignore-preflight-errors=cri --discovery-token-unsafe-skip-ca-verification --token={{ kubernetes_token }} {{ hostvars['master'].ansible_eth1.ipv4.address }}:6443

- name: iptables open ports
  command: iptables -A INPUT -p tcp -m state --state NEW -m multiport --dports 9000:9200 -j ACCEPT

- name: save iptables
  command: service iptables save

# Accept loop devices for the LVM ember-volumes VG and reject anything else
- name: Disable new LVM volumes
  lineinfile:
    path: /etc/lvm/lvm.conf
    state: present
    insertafter: '# filter ='
    line: "\tfilter = [ \"a|loop|\", \"r|.*\\/|\" ]\n\tglobal_filter = [ \"a|loop|\", \"r|.*\\/|\" ]"

# Workaround for lvcreate hanging inside contatiner
# https://serverfault.com/questions/802766/calling-lvcreate-from-inside-the-container-hangs
- lineinfile:
    path: /etc/lvm/lvm.conf
    state: present
    regexp: "^\tudev_sync = 1"
    line: "\tudev_sync = 0"

- lineinfile:
    path: /etc/lvm/lvm.conf
    state: present
    regexp: "^\tudev_rules = 1"
    line: "\tudev_rules = 0"

- name: Install iSCSI
  yum: name={{ item }} state=present
  with_items:
    - iscsi-initiator-utils
    - device-mapper-multipath

- name: Configure multipath
  command: mpathconf --enable --with_multipathd y --user_friendly_names n --find_multipaths y

- name: Enable connection services
  service: name={{ item }} state=restarted enabled=yes
  with_items:
    - iscsid
    - multipathd
