apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-node-rbd
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-node-rbd
rules:
  # Allow managing ember resources
  - apiGroups: ['ember-csi.io']
    resources: ['*']
    verbs: ['*']
  # Allow listing and creating CRDs
  - apiGroups: ['apiextensions.k8s.io']
    resources: ['customresourcedefinitions']
    verbs: ['list', 'create']
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-node-rbd
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: csi-node-rbd
subjects:
- kind: ServiceAccount
  name: csi-node-rbd
  namespace: default
---
# Node 0 will only be able to access RBD
# Nodes 1 onward will be able to access everything
kind: DaemonSet
apiVersion: apps/v1beta2
metadata:
  name: csi-node-rbd
  namespace: default
spec:
  selector:
    matchLabels:
      app: csi-node-rbd
  template:
    metadata:
      labels:
        app: csi-node-rbd
    spec:
      serviceAccount: csi-node-rbd
      # Required by iSCSI
      hostNetwork: true
      containers:
        - name: driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
          args:
          - --v=5
          - --csi-address=/csi-data/csi.sock
          - --kubelet-registration-path=/var/lib/kubelet/plugins/rbd.ember-csi.io/csi.sock
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /csi-data
              name: socket-dir
            - name: registration-dir
              mountPath: /registration
        - name: csi-driver
          image: "{{ ember_image }}"
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
          imagePullPolicy: Always
          env:
            - name: PYTHONUNBUFFERED
              value: '0'
            - name: X_CSI_SPEC_VERSION
              value: v1.0
            - name: CSI_ENDPOINT
              value: unix:///csi-data/csi.sock
            - name: CSI_MODE
              value: node
            - name: X_CSI_PERSISTENCE_CONFIG
              value: '{"storage":"crd"}'
            - name: X_CSI_NODE_TOPOLOGY
              value: '{"rbd":"true"}'
            - name: X_CSI_EMBER_CONFIG
              value: '{"plugin_name":"rbd","debug":{{ ember_debug_logs | to_json }},"enable_probe":true}'
            - name: X_CSI_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          livenessProbe:
            exec:
              command:
              - ember-liveness
            initialDelaySeconds: 120
            periodSeconds: 90
            timeoutSeconds: 60
          volumeMounts:
            - name: socket-dir
              mountPath: /csi-data
            - name: mountpoint-dir
              mountPath: /var/lib/kubelet
              mountPropagation: Bidirectional
            - name: dev-dir
              mountPath: /dev
              mountPropagation: Bidirectional
            - name: modules-dir
              mountPath: /lib/modules
              mountPropagation: HostToContainer
            - name: localtime
              mountPath: /etc/localtime
              mountPropagation: HostToContainer
            - name: udev-data
              mountPath: /run/udev
              mountPropagation: HostToContainer
            # So we don't lose our private bindmounts on container reboot
            - name: ember-csi-data
              mountPath: /var/lib/ember-csi
              mountPropagation: Bidirectional
        - name: csc
          image: embercsi/csc:v1.0.0
          command: ["tail"]
          args: ["-f", "/dev/null"]
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi-data/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi-data
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/rbd.ember-csi.io
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: dev-dir
          hostPath:
            path: /dev
        - name: modules-dir
          hostPath:
            path: /lib/modules
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: udev-data
          hostPath:
            path: /run/udev
        - name: ember-csi-data
          hostPath:
            path: /var/lib/ember-csi/rbd
