---
# tasks file for create-vm

- hosts: all
  connection: local

  tasks:
  - name: define vm
    virt:
        name: foo
        command: define
        xml: "{{ lookup('template', '{{playbook_dir}}/../templates/vm-template.xml.j2') }}"
        uri: 'qemu:///system'
  - name: start vm
    virt:
        name: foo
        state: running
        uri: 'qemu:///system'
