apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-node-sa
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-node-cr
rules:
  # Allow managing ember resources
  - apiGroups: ['ember-csi.io']
    resources: ['*']
    verbs: ['*']
  # Allow listing and creating CRDs
  - apiGroups: ['apiextensions.k8s.io']
    resources: ['customresourcedefinitions']
    verbs: ['list', 'create']
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-node-rb
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: csi-node-cr
subjects:
- kind: ServiceAccount
  name: csi-node-sa
  namespace: csi
---
kind: DaemonSet
apiVersion: apps/v1beta2
metadata:
  name: csi-node
  namespace: csi
spec:
  selector:
    matchLabels:
      app: csi-node
  template:
    metadata:
      labels:
        app: csi-node
    spec:
      serviceAccount: csi-node-sa
      hostNetwork: true
      containers:
        - name: driver-registrar
          image: quay.io/k8scsi/driver-registrar:v0.3.0
          securityContext:
            privileged: true
          args:
          - --v=5
          - --csi-address=/csi-data/csi.sock
          env:
          - name: KUBE_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          volumeMounts:
          - name: kubelet-sock-dir
            mountPath: /var/lib/kubelet/device-plugins
            mountPropagation: Bidirectional
          - mountPath: /csi-data
            name: socket-dir
          - name: mountpoint-dir
            mountPath: /var/lib/kubelet/pods
            mountPropagation: Bidirectional
        - name: csi-driver
          image: akrog/ember-csi:master
          terminationMessagePath: "/tmp/my-log"
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
          imagePullPolicy: Always
          env:
            - name: PYTHONUNBUFFERED
              value: '0'
            - name: CSI_ENDPOINT
              value: unix:///csi-data/csi.sock
            - name: CSI_MODE
              value: node
            - name: X_CSI_PERSISTENCE_CONFIG
              value: '{"storage":"crd"}'
            - name: X_CSI_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
                  #fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /csi-data
            - name: kubelet-sock-dir
              mountPath: /var/lib/kubelet/device-plugins
              mountPropagation: Bidirectional
            - name: mountpoint-dir
              mountPath: /var/lib/origin/openshift.local.volumes
              mountPropagation: Bidirectional
            - name: dev-dir
              mountPath: /dev
              mountPropagation: Bidirectional
            - name: modules-dir
              mountPath: /lib/modules
              mountPropagation: HostToContainer
            - name: localtime
              mountPath: /etc/localtime
              mountPropagation: HostToContainer
            - name: ceph-secrets
              mountPath: /etc/ceph
      volumes:
        - name: socket-dir
          hostPath:
            #path: /var/lib/origin/openshift.local.volumes/plugins/io.ember-csi
            path: /var/lib/kubelet/plugins/io.ember-csi
            type: DirectoryOrCreate
        - name: kubelet-sock-dir
          hostPath:
            path: /var/lib/kubelet/device-plugins
            type: Directory
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/origin/openshift.local.volumes/
            type: Directory
        - name: dev-dir
          hostPath:
            path: /dev
        - name: modules-dir
          hostPath:
            path: /lib/modules
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: ceph-secrets
          secret:
            secretName: ceph-secrets

