apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-from-snap-rbd
spec:
  storageClassName: csi-rbd
  dataSource:
    name: csi-rbd
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
