kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app-rbd-2
spec:
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: my-csi-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: my-csi-volume
      persistentVolumeClaim:
        claimName: vol-from-snap-rbd # defined in restore-snapshot-rbd.yml
