Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.provision "shell",path: "bootstrap.sh"
  config.vm.provision "shell",path: "tests.sh"
  config.vm.synced_folder "../", "/vagrant"
  config.vm.define "env-tests" do |admin|
    admin.vm.provider :libvirt do |domain|
     domain.memory = 2048
     domain.cpus = 1
     domain.nested = true
     domain.volume_cache = 'none'
    end
    admin.vm.provider :libvirt do |libvirt|
     libvirt.driver = "kvm"
     libvirt.uri = "qemu:///system"
     libvirt.connect_via_ssh = false
     libvirt.username = "root"
    end
  end
end
