apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-xtremio-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ember-csi-xtremio-sc
