apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: larger-vol-from-snap
spec:
  storageClassName: csi-sc
  dataSource:
    name: csi-snap
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
