apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: larger-vol-from-vol
spec:
  storageClassName: csi-sc
  volumeMode: Block
  dataSource:
    name: csi-block-pvc
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
