#!/usr/bin/env bash


# iSCSI IP addresses are being auto-selected here.
# Change the values if desired.
IPS=(`hostname -I`)
IP1=${IPS[1]}
IP2=${IPS[2]}

# This is the default, here just for reference
export CSI_MODE=all
# This is the default, here just for reference
export CSI_ENDPOINT='[::]:50051'

export X_CSI_PERSISTENCE_CONFIG="{\"storage\":\"db\",\"connection\":\"sqlite:///`realpath ../../tmp`/db.sqlite\"}"
export X_CSI_EMBER_CONFIG='{"project_id":"io.ember-csi","user_id":"io.ember-csi","root_helper":"sudo"}'
export X_CSI_BACKEND_CONFIG='{"iscsi_protocol":"iscsi","iscsi_ip_address":"$IP1","iscsi_secondary_ip_addresses":["$IP2"],"volume_backend_name":"CSI","volume_driver":"cinder.volume.drivers.lvm.LVMVolumeDriver","volume_group":"ember-volumes","iscsi_helper":"lioadm"}'
