#!/usr/bin/env bash

# This is the default, here just for reference
export CSI_MODE=all
# This is the default, here just for reference
export CSI_ENDPOINT='[::]:50051'

export X_CSI_SPEC_VERSION=v1.1

export X_CSI_PERSISTENCE_CONFIG="{\"storage\":\"db\",\"connection\":\"sqlite:///`realpath ../../tmp`/db.sqlite\"}"
# At the moment Cinder, and cinderlib by extension, don't work properly if the 
# ceph conf and keyring are not place under default /etc/ceph directory.
# This backend config uses the a pool that exists by default.  If the pool
# or rdb_user is changed - Ceph must be configured to match.
export X_CSI_BACKEND_CONFIG='{"name":"rbd","driver":"RBD","rbd_user":"admin","rbd_pool":"rbd","rbd_ceph_conf":"/etc/ceph/ceph.conf","rbd_keyring_conf":"/etc/ceph/ceph.client.admin.keyring"}'
