#!/usr/bin/env bash

# This is the default, here just for reference
export CSI_MODE=all
# This is the default, here just for reference
export CSI_ENDPOINT='[::]:50051'

export X_CSI_PERSISTENCE_CONFIG="{\"storage\":\"db\",\"connection\":\"sqlite:///`realpath ../../tmp`/db.sqlite\"}"
export X_CSI_BACKEND_CONFIG='{"name":"xtremio","driver":"XtremIOISCSI","san_ip":"192.168.1.22","xtremio_cluster_name":"cluster-name","san_login":"admin","san_password":"nomoresecrets"}'
