apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-sc
  namespace: default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: io.ember-csi
reclaimPolicy: Delete
volumeBindingMode: Immediate
