apiVersion: v1
kind: Template
metadata:
  name: ember-csi
parameters:
  - name:         PODNAME
    Display Name: pod name
    Description:  TEST environment pod name
    Required:     true
    Value:        "ember-csi"
objects:
  - apiVersion: "v1"
    kind: "Pod"
    metadata:
      name: ${PODNAME}
    spec:
      containers:
        - name: ember-csi
          image: quay.io/pod_utils/systemd-libvirt-centos-vm:1.0
          securityContext:
            privileged: true
          readinessProbe:
            exec:
              command:
              - test
              - -e
              - /var/tmp/vagrant-vm-up
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 50
