---

- hosts: all
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: define guest
    virt:
        name: foo
        command: define
        xml: "{{ lookup('template', '{{playbook_dir}}/../templates/vm-template.xml.j2') }}"
        uri: 'qemu:///system'

  - name: start guest
    virt:
        name: foo
        state: running
        uri: 'qemu:///system'

  - name: Locate the guest
    virt:
        command: list_vms
    register: vms

  - debug:
      var: vms

  # - name: add host to group 'ember-env'
  #   add_host:
  #     name: "{{ ip_from_ec2 }}"
  #     groups: ember-env
  #     foo: 42
