#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
. "$DIR/set-tags"

set -ev

# Only push when tagging a release or making changes to master branch
if [[ "$TRAVIS_BRANCH" == "$TRAVIS_TAG" || ("$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false") ]]; then
  for tag_info_string in $TAGS; do
    IFS=';' read -a tag_info <<< "$tag_info_string"
    echo "Pulling ${tag_info[1]}..."
    docker pull ${tag_info[1]}
    echo "Retagging and pushing ${tag_info[2]} ..."
    docker tag  ${tag_info[1]} ${tag_info[2]}
    docker push ${tag_info[2]}
  done

  if [ "${tag_info[3]}" != "unstable" ]; then
    echo "Setting stable tag ${tag_info[3]}"
    docker tag  ${tag_info[2]} ${EMBER_REPO}:${tag_info[3]}
    docker push ${EMBER_REPO}:${tag_info[3]}
  fi

else
  echo "This is not a tag or a merge to master, skipping pushing to ember-csi"
fi
