#!/usr/bin/env bash

if [ "$SOURCE_BRANCH" == "master" ]
then
  for tag in master latest; do
    echo "Building ember-csi $tag with cinderlib $tag ..."
    docker build --build-arg CINDERLIB_TAG=$tag -t $DOCKER_REPO:$tag -f Dockerfile .
  done

else
  releases=`curl https://raw.githubusercontent.com/Akrog/cinderlib/master/rdo-releases`
  cinderlib_pinned_stable_version=`cat hooks/cinderlib-pinned-stable-version`

  while read -r release; do
      cinderlib_tag="${release}-cl_${cinderlib_pinned_stable_version}"
      echo "Building $SOURCE_BRANCH with cinderlib $cinderlib_tag ..."
      docker build --build-arg CINDERLIB_TAG=$cinderlib_tag -t $DOCKER_REPO:$release --build-arg VERSION=$SOURCE_BRANCH -f Dockerfile-release .
  done <<< "$releases"
fi
