#!/usr/bin/env bash
set -e

EMBER_VERSION=`git describe --tags`

if [ "$SOURCE_BRANCH" == "master" ]
then
  STABLE_RELEASE=`tail -1 hooks/rdo-releases`
  docker build \
         --build-arg RELEASE=master \
         --build-arg VERSION=$EMBER_VERSION \
         --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
         --build-arg VCS_REF=`git rev-parse --short HEAD` \
         -t $DOCKER_REPO:master \
         -f Dockerfile .
  # Disable building from stable for now, since cinderlib has bugs there and
  # we cannot patch Stein yet
  # docker build \
  #        --build-arg RELEASE=$STABLE_RELEASE \
  #        --build-arg VERSION=$EMBER_VERSION \
  #        --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
  #        --build-arg VCS_REF=`git rev-parse --short HEAD` \
  #        -t $DOCKER_REPO:latest \
  #        -f Dockerfile .

else
  RDO_RELEASES=`cat hooks/rdo-releases`
  while read -r release; do
    echo "Building $SOURCE_BRANCH with cinderlib $release ..."
    docker build \
           --build-arg RELEASE=$release \
           --build-arg VERSION=$EMBER_VERSION \
           --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
           --build-arg VCS_REF=`git rev-parse --short HEAD` \
           --build-arg TAG=$SOURCE_BRANCH \
           -t $DOCKER_REPO:$release \
           -f Dockerfile-release .
  done <<< "$RDO_RELEASES"
fi
