#!/usr/bin/env bash
set -e
set -x


# Push ember-csi master branches
if [ "$SOURCE_BRANCH" == "master" ]; then
  TAG=master
  RETAG=latest
else
  TAG=`cat hooks/rdo-releases`
  RETAG=stable
fi

echo "Pushing $TAG ..."
docker push $DOCKER_REPO:$TAG

echo "Retagging it as $RETAG ..."
docker tag $DOCKER_REPO:$TAG $DOCKER_REPO:$RETAG

echo "Pushing tag $RETAG ..."
docker push $DOCKER_REPO:$RETAG
