apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-node-sa
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-node-cr
rules:
  # Allow managing ember resources
  - apiGroups: ['ember-csi.io']
    resources: ['*']
    verbs: ['*']
  # Allow listing and creating CRDs
  - apiGroups: ['apiextensions.k8s.io']
    resources: ['customresourcedefinitions']
    verbs: ['list', 'create']
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-node-rb
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: csi-node-cr
subjects:
- kind: ServiceAccount
  name: csi-node-sa
  namespace: default
---
# Nodes 1 and above can access the LVM iSCSI backend
kind: DaemonSet
apiVersion: apps/v1beta2
metadata:
  name: csi-node
  namespace: default
spec:
  selector:
    matchLabels:
      app: csi-node
  template:
    metadata:
      labels:
        app: csi-node
    spec:
      serviceAccount: csi-node-sa
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - node0
      # Required by iSCSI
      hostNetwork: true
      # Required by multipath detach
      hostIPC: true
      containers:
        - name: driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.0.2
          args:
          - --v=5
          - --csi-address=/csi-data/csi.sock
          - --kubelet-registration-path=/var/lib/kubelet/plugins/ember-csi.io/csi.sock
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /csi-data
              name: socket-dir
            - name: registration-dir
              mountPath: /registration
        - name: csi-driver
          image: "{{ ember_image }}"
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
          imagePullPolicy: Always
          env:
            - name: PYTHONUNBUFFERED
              value: '0'
            - name: X_CSI_SPEC_VERSION
              value: v1.0
            - name: CSI_ENDPOINT
              value: unix:///csi-data/csi.sock
            - name: CSI_MODE
              value: node
            - name: X_CSI_PERSISTENCE_CONFIG
              value: '{"storage":"crd"}'
            - name: X_CSI_NODE_TOPOLOGY
              value: '{"iscsi":"true"}'
            - name: X_CSI_EMBER_CONFIG
              value: '{"debug":{{ ember_debug_logs | to_json }},"enable_probe":true}'
            - name: X_CSI_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          livenessProbe:
            exec:
              command:
              - ember-liveness
            initialDelaySeconds: 120
            periodSeconds: 90
            timeoutSeconds: 60
          volumeMounts:
            - name: socket-dir
              mountPath: /csi-data
            - name: mountpoint-dir
              mountPath: /var/lib/kubelet
              mountPropagation: Bidirectional
            - name: iscsi-dir
              mountPath: /etc/iscsi
              mountPropagation: Bidirectional
            - name: dev-dir
              mountPath: /dev
              mountPropagation: Bidirectional
            - name: lvm-conf
              mountPath: /etc/lvm/lvm.conf
              mountPropagation: HostToContainer
            - name: lvm-lock
              mountPath: /var/lock/lvm
              mountPropagation: Bidirectional
            - name: multipath-dir
              mountPath: /etc/multipath
              mountPropagation: Bidirectional
            - name: multipath-conf
              mountPath: /etc/multipath.conf
              mountPropagation: HostToContainer
            - name: modules-dir
              mountPath: /lib/modules
              mountPropagation: HostToContainer
            - name: localtime
              mountPath: /etc/localtime
              mountPropagation: HostToContainer
            - name: udev-data
              mountPath: /run/udev
              mountPropagation: HostToContainer
            # Required to preserve the node targets between restarts
            - name: iscsi-info
              mountPath: /var/lib/iscsi
              mountPropagation: Bidirectional
            # In a real deployment we should be mounting container's
            # /var/lib-ember-csi on the host
        - name: csc
          image: embercsi/csc:v1.0.0
          command: ["tail"]
          args: ["-f", "/dev/null"]
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi-data/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi-data
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/ember-csi.io
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: iscsi-dir
          hostPath:
            path: /etc/iscsi
            type: Directory
        - name: dev-dir
          hostPath:
            path: /dev
        - name: lvm-conf
          hostPath:
            path: /etc/lvm/lvm.conf
        - name: lvm-lock
          hostPath:
            path: /var/lock/lvm
        - name: multipath-dir
          hostPath:
            path: /etc/multipath
        - name: multipath-conf
          hostPath:
            path: /etc/multipath.conf
        - name: modules-dir
          hostPath:
            path: /lib/modules
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: udev-data
          hostPath:
            path: /run/udev
        - name: iscsi-info
          hostPath:
            path: /var/lib/iscsi
---
# Node 0 cannot access LVM iSCSI backend
# We need this pod because CSI needs all nodes to be running the plugin
kind: DaemonSet
apiVersion: apps/v1beta2
metadata:
  name: csi-node-0
  namespace: default
spec:
  selector:
    matchLabels:
      app: csi-node
  template:
    metadata:
      labels:
        app: csi-node
    spec:
      serviceAccount: csi-node-sa
      nodeSelector:
        kubernetes.io/hostname: node0
      # Required by iSCSI
      hostNetwork: true
      # Required by multipath detach
      hostIPC: true
      containers:
        - name: driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.0.2
          args:
          - --v=5
          - --csi-address=/csi-data/csi.sock
          - --kubelet-registration-path=/var/lib/kubelet/plugins/ember-csi.io/csi.sock
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /csi-data
              name: socket-dir
            - name: registration-dir
              mountPath: /registration
        - name: csi-driver
          image: "{{ ember_image }}"
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
          imagePullPolicy: Always
          env:
            - name: PYTHONUNBUFFERED
              value: '0'
            - name: X_CSI_SPEC_VERSION
              value: v1.0
            - name: CSI_ENDPOINT
              value: unix:///csi-data/csi.sock
            - name: CSI_MODE
              value: node
            - name: X_CSI_PERSISTENCE_CONFIG
              value: '{"storage":"crd"}'
            - name: X_CSI_NODE_TOPOLOGY
              value: '{"iscsi":"false"}'
            - name: X_CSI_EMBER_CONFIG
              value: '{"debug":{{ ember_debug_logs | to_json }},"enable_probe":true}'
            - name: X_CSI_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          livenessProbe:
            exec:
              command:
              - ember-liveness
            initialDelaySeconds: 120
            periodSeconds: 90
            timeoutSeconds: 60
          volumeMounts:
            - name: socket-dir
              mountPath: /csi-data
            - name: mountpoint-dir
              mountPath: /var/lib/kubelet
              mountPropagation: Bidirectional
            - name: iscsi-dir
              mountPath: /etc/iscsi
              mountPropagation: Bidirectional
            - name: dev-dir
              mountPath: /dev
              mountPropagation: Bidirectional
            - name: lvm-conf
              mountPath: /etc/lvm/lvm.conf
              mountPropagation: HostToContainer
            - name: lvm-lock
              mountPath: /var/lock/lvm
              mountPropagation: Bidirectional
            - name: multipath-dir
              mountPath: /etc/multipath
              mountPropagation: Bidirectional
            - name: multipath-conf
              mountPath: /etc/multipath.conf
              mountPropagation: HostToContainer
            - name: modules-dir
              mountPath: /lib/modules
              mountPropagation: HostToContainer
            - name: localtime
              mountPath: /etc/localtime
              mountPropagation: HostToContainer
            - name: udev-data
              mountPath: /run/udev
              mountPropagation: HostToContainer
            # Required to preserve the node targets between restarts
            - name: iscsi-info
              mountPath: /var/lib/iscsi
              mountPropagation: Bidirectional
            # In a real deployment we should be mounting container's
            # /var/lib-ember-csi on the host
        - name: csc
          image: embercsi/csc:v1.0.0
          command: ["tail"]
          args: ["-f", "/dev/null"]
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi-data/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi-data
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/ember-csi.io
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: iscsi-dir
          hostPath:
            path: /etc/iscsi
            type: Directory
        - name: dev-dir
          hostPath:
            path: /dev
        - name: lvm-conf
          hostPath:
            path: /etc/lvm/lvm.conf
        - name: lvm-lock
          hostPath:
            path: /var/lock/lvm
        - name: multipath-dir
          hostPath:
            path: /etc/multipath
        - name: multipath-conf
          hostPath:
            path: /etc/multipath.conf
        - name: modules-dir
          hostPath:
            path: /lib/modules
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: udev-data
          hostPath:
            path: /run/udev
        - name: iscsi-info
          hostPath:
            path: /var/lib/iscsi
