Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.synced_folder "/root/ember-csi", "/vagrant"
  config.vm.provision "shell",path: "automation/bootstrap.sh"
  config.vm.provision "shell",path: "automation/tests.sh"
end
