Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.provision "shell",path: "ci-automation/tests/bootstrap.sh"
  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = 4096
    libvirt.cpus = 4
    libvirt.nested = true
    libvirt.cpu_mode = "host-passthrough"
    libvirt.volume_cache = 'none'
    libvirt.driver = "kvm"
    libvirt.uri = "qemu:///system"
    libvirt.connect_via_ssh = false
    libvirt.username = "root"
  end
end
