Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.provision "shell",path: "ci-automation/tests/bootstrap.sh"
  config.vm.define "ci-tests" do |admin|
    admin.vm.provider :libvirt do |domain|
     domain.memory = 4096
     domain.cpus = 4
     domain.nested = true
     domain.volume_cache = 'none'
    end
    admin.vm.provider :libvirt do |libvirt|
     libvirt.driver = "kvm"
     libvirt.uri = "qemu:///system"
     libvirt.connect_via_ssh = false
     libvirt.username = "root"
    end
  end
end
