- hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - "global_vars.yml"
  roles:
    - common

- hosts: master_node
  become: yes
  become_method: sudo
  vars_files:
    - "global_vars.yml"
  roles:
    - master
  environment:
    KUBECONFIG: '/etc/kubernetes/admin.conf'

- hosts: nodes
  become: yes
  become_method: sudo
  vars_files:
    - "global_vars.yml"
  roles:
    - nodes

- hosts: node0
  become: yes
  tasks:
    - import_tasks: setup_lvm.yml

- hosts: master_node
  become: yes
  tasks:
    - import_tasks: setup_csi.yml
